# Generated by Django 5.2.4 on 2025-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20250806_1104"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="label",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
