# Generated by Django 5.2.4 on 2025-08-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store",
            "0007_rename_label_collection_renamed_to_title_and_customer_phone_to_charfield",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
